export let data = {
  Skilling: [
    'Abyssal protector',
    'Baby chinchompa',
    'Beaver',
    'Giant squirrel',
    'Herbi',
    'Heron', 
    'Phoenix', 
    'Rift guardian',
    'Rock golem',
    'Rocky',
    'Tangleroot',
    'Tiny tempor', 
  ],
  Slayer: [
    'Abyssal orphan',
    'Hellpuppy',
    'Ikkle hydra',
    'Kalphite princess',
    'Noon', 
    'Pet kraken', 
    'Pet smoke devil',
  ],
  Raids: [
    'Lil\' zik',
    'Olmlet',
    'Tumeken\'s guardian',
  ],
  Bosses: [
    'Baby mole',
    'Muphin',
    'Little nightmare',
    'Pet dark core',
    'Pet dagannoth prime', 
    'Pet dagannoth rex',
    'Pet dagannoth supreme',
    'Pet snakeling', 
    'Skotos', 
    'Smolcano', 
    'Sraracha', 
    'Tzrek-jad',
    'Jal-nib-rek',
    'Vorki', 
    'Youngllef',
  ],
  Wilderness: [
    'Pet chaos elemental', 
    'Callisto cub',
    'Prince black dragon',
    'Scorpia\'s offspring',
    'Venenatis spiderling',
    'Vet\'ion jr.',

  ],
  GodWars: [
    'Nexling', 
    'Pet k\'ril tsutsaroth', 
    'Pet general graardor',
    'Pet kree\'arra', 
    'Pet zilyana', 
  ],
  Other: [
    'Bloodhound',
    'Chompy chick',
    'Lil\' creator',
    'Pet penance queen'
  ],
  DT2: [
    'Lil\'viathan',
    'Wisp',
    'Butch',
    'Baron'
  ]
}
