[uwsgi]
# Use server.py directly since we've made it production safe!
module = server:app

master = true
processes = 4
enable-threads = true
lazy-apps = true

# Inside Docker, it's best to bind to a TCP port instead of a Unix socket 
# so Nginx on the host can communicate with the container easily.
http = 0.0.0.0:8000

# (Alternative) If you want to use uwsgi_pass instead of proxy_pass in Nginx:
# uwsgi-socket = 0.0.0.0:8000

vacuum = true
die-on-term = true
