[uwsgi]
module = server:app

master = true
processes = 2
gevent = 1000
enable-threads = true
lazy-apps = true

# Inside Docker, it's best to bind to a TCP port instead of a Unix socket 
# so Nginx on the host can communicate with the container easily.
http = 0.0.0.0:8000

vacuum = true
die-on-term = true
