name: Deploy to Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: |
            cd /var/www/server/github-pages
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build --no-deps api worker