name: Deploy Frontend

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/src/**'
      - 'apps/frontend/public/**'
      - 'apps/frontend/package.json'
      - 'apps/frontend/package-lock.json'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json
          
      - name: Build Frontend
        working-directory: apps/frontend
        run: |
          npm install
          CI=false npm run build
          
      # Clean the old files first
      - name: Clean old frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          script: rm -rf /var/www/frontend/*

      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          source: "apps/frontend/dist/*"
          target: "/var/www/frontend"
          strip_components: 3
